apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-containers-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: hello-containers
spec:
  project: default
  destination:
    name: in-cluster
    namespace: hello-test
  source:
    path: manifests/test
    repoURL: https://github.com/BobJWalker/Hello-Containers.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
